// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9De5YX7Fmqyf_yOVAtQZmWiDeq-x5So',
    appId: '1:175501093692:web:3d6364e3eb0d6d50460c39',
    messagingSenderId: '175501093692',
    projectId: 'flunny-23452',
    authDomain: 'flunny-23452.firebaseapp.com',
    storageBucket: 'flunny-23452.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54MWtPPHXkKxG5h-QSwQdnj1lrLZrkqs',
    appId: '1:175501093692:android:2be801f78ed61c8c460c39',
    messagingSenderId: '175501093692',
    projectId: 'flunny-23452',
    storageBucket: 'flunny-23452.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnWm2Pz2wiBT9_cmCEftMBPeuZH_hIs1w',
    appId: '1:175501093692:ios:0038f04a7a410d4e460c39',
    messagingSenderId: '175501093692',
    projectId: 'flunny-23452',
    storageBucket: 'flunny-23452.appspot.com',
    androidClientId: '175501093692-gm55h9n9tisq7s5l85jj5m1ah5s4vu23.apps.googleusercontent.com',
    iosClientId: '175501093692-l4poijeq2ta6vkpcc6uct0h49iuleo1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnWm2Pz2wiBT9_cmCEftMBPeuZH_hIs1w',
    appId: '1:175501093692:ios:0038f04a7a410d4e460c39',
    messagingSenderId: '175501093692',
    projectId: 'flunny-23452',
    storageBucket: 'flunny-23452.appspot.com',
    androidClientId: '175501093692-gm55h9n9tisq7s5l85jj5m1ah5s4vu23.apps.googleusercontent.com',
    iosClientId: '175501093692-l4poijeq2ta6vkpcc6uct0h49iuleo1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluny',
  );
}
